### PR TITLE
add support for kcm (klikogroep / klikocontainermanager)

### LINKED ISSUE #337: Add support for Kliko Container Manager
### Feature request

My municipality uses KlikoContainerManager (by Kliko Group) starting from 2025. If I'm correct this is not supported yet. Could you add support for it?

### What version of the integration are you using?

2024.12.01

### Anything in the logs that might be useful for us?

_No response_

### Additional information

https://klikocontainermanager.com/

My municipality uses a custom subdomain.

### PR DESCRIPTION
**Pull request by sndrsmnk**
Fixes #337 

Other cities using KCM/klikogroep will need code changes.

I haven't (couldn't really) test if this breaks any other collectors. Please apply critical review. But it works for me. :+1:

### CODE REVIEW

**Comment by sndrsmnk** [comment]
KCM/KlikoGroep calls for a "card number", but i decided to name that field "username", as it could actually be viewed as such. This allows other collectors with the same user/pass requirement to be implemented more cleanly.

**Comment by sndrsmnk** [comment]
Also, i dont fully understand the result set (`getMyWasteCalendar`). It returns an array of arrays, which has two items per array, one of which is always 0 (in my case).  It could be that different cities collect two types of trash on the same day, perhaps?  I dont know hof afvalwijzer deals with multiple collection items on one day. [This change *could* introduce that situation](https://github.com/xirixiz/homeassistant-afvalwijzer/pull/361/files#diff-89b3d7f0e148bd4597f9be4fb422cc7b43df8e2c52d3db4692d4e22941ea5dcfR74)

**Comment by xirixiz** [comment]
@sndrsmnk thanks for your contribution! I`ll do some testing later Today, but my assumption is that it will not break anything.
We'll see if "getMyWasteCalendar" is needed later. People start creating issues anyway when it is really an issue, so don't worry. I`m very happy that you contributed to this project! Many thanks.

**Comment by xirixiz** [comment]
Pre-release created: 2024.12.07-pre.1

**Comment by xirixiz** [comment]
Made some improvements/modifications in regards to error handling. But the pre-release seems to be working just fine.
If you can confirm everything is working from your end, I`ll draft a new release.

https://github.com/xirixiz/homeassistant-afvalwijzer/blob/main/custom_components/afvalwijzer/collector/klikogroep.py

**Pull request merged**
